version: "3.9"

services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

    restart: always

    env_file:
      - ./.env.prod

  db:
    image: postgis/postgis:15-3.4
    restart: always
    env_file:
      - ./.env.prod
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
