# Generated by Django 5.1.4 on 2025-08-17 22:13

import location_field.models.spatial
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='location',
            field=location_field.models.spatial.LocationField(srid=4326),
        ),
    ]
