# Generated by Django 5.1.4 on 2025-08-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
