# Generated by Django 5.1.4 on 2025-08-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_favorite_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
