# Generated by Django 5.1.4 on 2025-08-22 22:57

import location_field.models.spatial
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_review_comment_alter_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='location',
            field=location_field.models.spatial.LocationField(geography=True, srid=4326),
        ),
    ]
