# Generated by Django 5.1.4 on 2025-08-27 00:42

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_alter_review_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='business',
            index=django.contrib.postgres.indexes.GistIndex(fields=['location'], name='business_bu_locatio_da51f1_gist'),
        ),
    ]
