# Generated by Django 5.1 on 2024-08-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_advertcategory_merchant_advertiser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiser',
            name='is_activated',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='is_activated',
        ),
        migrations.AddField(
            model_name='merchant',
            name='merchant_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
