# Generated by Django 5.1 on 2024-08-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_resetpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
