# Generated by Django 5.1 on 2024-08-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_resetpassword_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpassword',
            name='token',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
