# Generated by Django 5.1 on 2024-08-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_resetpassword_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='otp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
