# Generated by Django 5.1 on 2024-08-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_resetpassword_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='category',
            field=models.ManyToManyField(blank=True, to='users.advertcategory'),
        ),
    ]
