# Generated by Django 5.1 on 2024-12-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_resetpassword_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpassword',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
