# Generated by Django 5.1.4 on 2025-08-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_resetpassword_is_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_activated',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('customer', 'Customer')], default='customer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.TextField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], null=True),
        ),
    ]
