# Generated by Django 5.1.4 on 2025-08-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_user_is_activated_user_role_alter_user_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResetPassword',
        ),
    ]
